<a href="https://colab.research.google.com/github/sydoky/Neural-network-regression-with-TensorFlow-Exericices/blob/main/Neural_network_regression_with_TensorFlow_Exericices.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import tensorflow as tf


1.Create regression dataset (or make the one we created in "Create data to view and fit bigger) and build fit a model to it

In [2]:
import numpy as np
import matplotlib.pyplot as plt
from sklearn.datasets import make_regression
X,y=make_regression(n_samples=200,
                    n_features=10,
                    n_targets=1)

X

array([[-1.19627556,  1.02913339,  0.15788117, ...,  1.20500429,
         1.73529719,  0.19701805],
       [ 1.28475897,  0.21927439,  1.09819416, ..., -1.2083827 ,
         1.48585931,  1.2191096 ],
       [ 1.37436748, -1.23339281,  0.02430973, ..., -1.04625435,
        -0.0326269 ,  1.41857514],
       ...,
       [-0.00405807,  0.33297052, -0.42588841, ..., -1.25282069,
         1.65467206, -0.51336569],
       [ 0.08124196,  0.46791437, -0.20709338, ..., -0.41455729,
         0.62692168,  0.24665036],
       [-0.40268992, -1.99585022, -2.8294909 , ...,  0.09484962,
        -1.67836077,  0.81191239]])

In [3]:
y

array([ 283.76986234,  102.14146553, -106.33262923,  103.25872778,
        -58.8235573 ,  258.19958839, -125.811211  ,   54.01277929,
        145.11670989,  228.48531582, -124.34745075,  236.25851499,
        -46.72509014,   53.62027732,  -85.63711817,  123.18750904,
        278.62378878, -463.9078165 ,   29.00726898,  141.33537763,
        162.80106531,  -87.64577998, -161.14608163,  235.6205175 ,
        149.46133883, -133.49674381, -222.59900026,  -91.68643749,
         92.06045312,   -5.41996104,  178.60157797, -144.71393934,
        137.79609356, -247.72968327,  375.21221521,   33.87692079,
         88.42740123,   -2.70662503,  106.39911124,   85.22592599,
       -244.87806143, -234.43648363,  -38.17476678,    5.10459692,
       -213.67289265,  -42.36914214,   23.15134525,   96.19712425,
       -181.64939729,  -83.31815172,   70.49537606, -224.0922572 ,
          4.97656015,   89.05434825,  -90.07524485,  156.03149845,
       -195.55967355,  -40.55774728,  -60.1909901 ,  -80.45283

In [4]:
tf.random.set_seed(42)

model_s=tf.keras.Sequential([
                             tf.keras.layers.Dense(1)
])

model_s.compile(loss=tf.keras.losses.mae,
                optimizer=tf.keras.optimizers.SGD(),
                metrics=["mae"])

model_s.fit(X,y, epochs=100)

Epoch 1/100
7/7 [==============================] - 1s 2ms/step - loss: 122.3482 - mae: 122.3482
Epoch 2/100
7/7 [==============================] - 0s 2ms/step - loss: 122.2998 - mae: 122.2998
Epoch 3/100
7/7 [==============================] - 0s 4ms/step - loss: 122.2520 - mae: 122.2520
Epoch 4/100
7/7 [==============================] - 0s 2ms/step - loss: 122.2050 - mae: 122.2050
Epoch 5/100
7/7 [==============================] - 0s 2ms/step - loss: 122.1597 - mae: 122.1597
Epoch 6/100
7/7 [==============================] - 0s 2ms/step - loss: 122.1115 - mae: 122.1115
Epoch 7/100
7/7 [==============================] - 0s 2ms/step - loss: 122.0655 - mae: 122.0655
Epoch 8/100
7/7 [==============================] - 0s 2ms/step - loss: 122.0172 - mae: 122.0172
Epoch 9/100
7/7 [==============================] - 0s 2ms/step - loss: 121.9698 - mae: 121.9698
Epoch 10/100
7/7 [==============================] - 0s 2ms/step - loss: 121.9222 - mae: 121.9222
Epoch 11/100
7/7 [=====================

2. Try building a neural network with 4 Dense layers and fitting it to your own regression dataset, how does it perform? 

In [5]:
tf.random.set_seed(42)

model_s_2=tf.keras.Sequential([
                               tf.keras.layers.Dense(100),
                               tf.keras.layers.Dense(50),
                               tf.keras.layers.Dense(10),
                               tf.keras.layers.Dense(1)
])

model_s_2.compile(loss=tf.keras.losses.mae,
                optimizer=tf.keras.optimizers.SGD(),
                metrics=["mae"])

model_s_2.fit(X,y,epochs=100)

Epoch 1/100
7/7 [==============================] - 1s 2ms/step - loss: 122.3374 - mae: 122.3374
Epoch 2/100
7/7 [==============================] - 0s 2ms/step - loss: 122.0557 - mae: 122.0557
Epoch 3/100
7/7 [==============================] - 0s 2ms/step - loss: 121.7344 - mae: 121.7344
Epoch 4/100
7/7 [==============================] - 0s 2ms/step - loss: 121.3111 - mae: 121.3111
Epoch 5/100
7/7 [==============================] - 0s 2ms/step - loss: 120.6996 - mae: 120.6996
Epoch 6/100
7/7 [==============================] - 0s 2ms/step - loss: 119.6090 - mae: 119.6090
Epoch 7/100
7/7 [==============================] - 0s 2ms/step - loss: 117.6071 - mae: 117.6071
Epoch 8/100
7/7 [==============================] - 0s 3ms/step - loss: 112.5972 - mae: 112.5972
Epoch 9/100
7/7 [==============================] - 0s 6ms/step - loss: 95.0321 - mae: 95.0321
Epoch 10/100
7/7 [==============================] - 0s 3ms/step - loss: 28.2574 - mae: 28.2574
Epoch 11/100
7/7 [=========================

3. Try and imporve the results we got on the dataset, some things you might want to try include:
-Building a larger model (how does one with 4 dense layers go?)

-Increasing the number of units in each layer

-Lookup the documentation of Adam and find out what the first parameter is, what happens if you increase it by 10x?

-What happens if you train for longer (Let's say 300 epochs instead of 200)? 

In [6]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [7]:
#Create a neural network model

tf.random.set_seed(42)

model_s=tf.keras.Sequential([
                             tf.keras.layers.Dense(1)
])

model_s.compile(loss=tf.keras.losses.mae,
                optimizer=tf.keras.optimizers.Adam(),
                metrics=["mae"])
model_s.fit(tf.expand_dims(X,axis=1),y,epochs=300)
 

Epoch 1/300
7/7 [==============================] - 1s 2ms/step - loss: 122.3366 - mae: 122.3366
Epoch 2/300
7/7 [==============================] - 0s 2ms/step - loss: 122.3263 - mae: 122.3263
Epoch 3/300
7/7 [==============================] - 0s 2ms/step - loss: 122.3352 - mae: 122.3352
Epoch 4/300
7/7 [==============================] - 0s 2ms/step - loss: 122.3527 - mae: 122.3527
Epoch 5/300
7/7 [==============================] - 0s 4ms/step - loss: 122.3204 - mae: 122.3204
Epoch 6/300
7/7 [==============================] - 0s 3ms/step - loss: 122.3337 - mae: 122.3337
Epoch 7/300
7/7 [==============================] - 0s 4ms/step - loss: 122.3313 - mae: 122.3313
Epoch 8/300
7/7 [==============================] - 0s 5ms/step - loss: 122.3373 - mae: 122.3373
Epoch 9/300
7/7 [==============================] - 0s 2ms/step - loss: 122.3175 - mae: 122.3175
Epoch 10/300
7/7 [==============================] - 0s 2ms/step - loss: 122.3331 - mae: 122.3331
Epoch 11/300
7/7 [=====================

In [8]:
#what happens if you increase it by 10x?
tf.random.set_seed(42)

model_s=tf.keras.Sequential([
                             tf.keras.layers.Dense(1)
])

model_s.compile(loss=tf.keras.losses.mae,
                optimizer=tf.keras.optimizers.Adam(
                    learning_rate=0.001*10,
                    beta_1=0.9,
                    beta_2=0.999,
                    epsilon=1e-07,
                    amsgrad=False,
                    name="Adam"),
                metrics=["mae"])
model_s.fit(tf.expand_dims(X,axis=1),y,epochs=300)




Epoch 1/300
7/7 [==============================] - 0s 2ms/step - loss: 122.3360 - mae: 122.3360
Epoch 2/300
7/7 [==============================] - 0s 2ms/step - loss: 122.3226 - mae: 122.3226
Epoch 3/300
7/7 [==============================] - 0s 2ms/step - loss: 122.3289 - mae: 122.3289
Epoch 4/300
7/7 [==============================] - 0s 2ms/step - loss: 122.3469 - mae: 122.3469
Epoch 5/300
7/7 [==============================] - 0s 2ms/step - loss: 122.3145 - mae: 122.3145
Epoch 6/300
7/7 [==============================] - 0s 1ms/step - loss: 122.3297 - mae: 122.3297
Epoch 7/300
7/7 [==============================] - 0s 2ms/step - loss: 122.3243 - mae: 122.3243
Epoch 8/300
7/7 [==============================] - 0s 3ms/step - loss: 122.3296 - mae: 122.3296
Epoch 9/300
7/7 [==============================] - 0s 3ms/step - loss: 122.3091 - mae: 122.3091
Epoch 10/300
7/7 [==============================] - 0s 2ms/step - loss: 122.3162 - mae: 122.3162
Epoch 11/300
7/7 [=====================

4. Import the Boston pricing dataset from TensorFlow tf.keras.datasets and model it

In [11]:
df=tf.keras.datasets.boston_housing.load_data(path="boston_housing.npz",test_split=0.2,seed=113)

df


65536/57026 [==================================] - 0s 0us/step


((array([[1.23247e+00, 0.00000e+00, 8.14000e+00, ..., 2.10000e+01,
          3.96900e+02, 1.87200e+01],
         [2.17700e-02, 8.25000e+01, 2.03000e+00, ..., 1.47000e+01,
          3.95380e+02, 3.11000e+00],
         [4.89822e+00, 0.00000e+00, 1.81000e+01, ..., 2.02000e+01,
          3.75520e+02, 3.26000e+00],
         ...,
         [3.46600e-02, 3.50000e+01, 6.06000e+00, ..., 1.69000e+01,
          3.62250e+02, 7.83000e+00],
         [2.14918e+00, 0.00000e+00, 1.95800e+01, ..., 1.47000e+01,
          2.61950e+02, 1.57900e+01],
         [1.43900e-02, 6.00000e+01, 2.93000e+00, ..., 1.56000e+01,
          3.76700e+02, 4.38000e+00]]),
  array([15.2, 42.3, 50. , 21.1, 17.7, 18.5, 11.3, 15.6, 15.6, 14.4, 12.1,
         17.9, 23.1, 19.9, 15.7,  8.8, 50. , 22.5, 24.1, 27.5, 10.9, 30.8,
         32.9, 24. , 18.5, 13.3, 22.9, 34.7, 16.6, 17.5, 22.3, 16.1, 14.9,
         23.1, 34.9, 25. , 13.9, 13.1, 20.4, 20. , 15.2, 24.7, 22.2, 16.7,
         12.7, 15.6, 18.4, 21. , 30.1, 15.1, 18.7,  9.6, 31.

In [12]:
(X_train,y_train),(X_test,y_test)=df


In [17]:
tf.random.set_seed(42)

boston_model = tf.keras.Sequential([
                                    tf.keras.layers.Dense(10),
                                    tf.keras.layers.Dense(10),
                                    tf.keras.layers.Dense(10),
                                    tf.keras.layers.Dense(1)
])

boston_model.compile(loss=tf.keras.losses.mae,
                     optimizer=tf.keras.optimizers.Adam(),
                     metrics=["mae"])

boston_model.fit(X_train, y_train, epochs=300)

Epoch 1/300
13/13 [==============================] - 0s 2ms/step - loss: 37.5704 - mae: 37.5704
Epoch 2/300
13/13 [==============================] - 0s 2ms/step - loss: 17.5845 - mae: 17.5845
Epoch 3/300
13/13 [==============================] - 0s 2ms/step - loss: 11.9465 - mae: 11.9465
Epoch 4/300
13/13 [==============================] - 0s 1ms/step - loss: 8.8825 - mae: 8.8825
Epoch 5/300
13/13 [==============================] - 0s 2ms/step - loss: 8.1822 - mae: 8.1822
Epoch 6/300
13/13 [==============================] - 0s 1ms/step - loss: 7.7106 - mae: 7.7106
Epoch 7/300
13/13 [==============================] - 0s 2ms/step - loss: 7.5139 - mae: 7.5139
Epoch 8/300
13/13 [==============================] - 0s 2ms/step - loss: 7.3910 - mae: 7.3910
Epoch 9/300
13/13 [==============================] - 0s 2ms/step - loss: 6.9479 - mae: 6.9479
Epoch 10/300
13/13 [==============================] - 0s 2ms/step - loss: 6.8371 - mae: 6.8371
Epoch 11/300
13/13 [==============================] -

In [18]:
boston_model.evaluate(X_test, y_test)

4/4 [==============================] - 0s 2ms/step - loss: 3.9292 - mae: 3.9292


[3.929238796234131, 3.929238796234131]